# -- Theme Parameters --
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
highlightCurrentMenuArea = true
smartTOC = true

mainSections = ["projects", "blog"]
logo = "img/logo.svg"
disableTextInHeader = true
hotlinkFeatureImage = true

defaultSocialImage = "img/logo.svg"

[homepage]
  layout = "background"
  homepageImage = "img/bg.jpg"
  layoutBackgroundBlur = true

  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showEdit = false
  showComments = false

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = true
  cardView = true
  showSummary = true

[taxonomy]
  showTermCount = true

[header]
  layout = "fixed"

[footer]
  showThemeAttribution = false
  showMenu = true
  showCopyright = true

copyright = "{ year } Waseem Al-Dmeiri. All rights reserved."
